theme: jekyll-theme-dinky
title: Talent identification research at Schmidt Futures
description: Notes on our work to identify accurate, fair and low-cost methods of measuring potential in young people
